### ISSUE TITLE
Bug collection for latest version

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/Industry-Game#12]
* Graphical weirdness (as mentioned in the commit message)
* Game will crash sometimes after opening and closing building dialogue (still need to reproduce)
* Draw pipes when closing building dialogue

**Comment by robtech21** [comment]
Reproducing game crash:

* Draw pipes between any two buildings
* Do literally anything else

Edit: Figured out this worked with any buildings

**Comment by Jackal-42** [comment]
I will look into these. Make sure to open each topic in a separate issue in the future.

**Comment by Jackal-42** [comment]
I haven't been able to recreate the game crash on the latest version. See if you can get it to happen and provide more detail.

**Comment by Jackal-42** [comment]
I think I found it. The crash only happens when you attempt to draw next to a facility with an existing pipe connection. I can see why that would make it hard to debug. It will be fixed asap

**Comment by Jackal-42** [comment]
This is all completed except for graphical bugs. Will make a new Issue for that
