### ISSUE TITLE
Increase focus area in tutorial

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/Industry-Game#21]
I think the focus area needs to be increased to the full 1x2 area when placing down the hydrotreater and distiller 

![Screenshot 2022-02-08 8 45 05 AM](https://user-images.githubusercontent.com/77758464/152999394-86bfdd27-4081-4fa3-bb5d-dc2edc6553e8.png)
![Screenshot 2022-02-08 8 42 53 AM](https://user-images.githubusercontent.com/77758464/152999397-fddf5ab0-0e06-4d22-8417-9b193e214ed4.png)

**Comment by Jackal-42** [comment]
True - this is how it was initially. However, it does not work because players will try to click on the bottom square and spawn it in the incorrect location. While with some effort a workaround could be achieved, it is not worth our time
