### ISSUE TITLE
Allow skipping tutorial

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/Industry-Game#22]
It's helpful for debugging or if you already know the game.

**Comment by Jackal-42** [comment]
Yeah I did that but I think I didn't commit yet. I will commit later today. It will be under the first drop down in the debug menu

**Comment by robtech21** [comment]
> Yeah I did that but I think I didn't commit yet. I will commit later today. It will be under the first drop down in the debug menu

That'll work for now. On the topic of debug menu, when we finish the game can we have a function that you can invoke in the JS console that makes the debug menu appear?

**Comment by Jackal-42** [comment]
Oh yeah I forgot that I removed its visibility. I will make it so that the command debugging=true will make it show up

**Comment by robtech21** [comment]
> Oh yeah I forgot that I removed its visibility. I will make it so that the command debugging=true will make it show up

It still exists, I'm just making sure there's a way to invoke it when it's gone.

**Comment by robtech21** [comment]
Already implemented, closing issue.
