### ISSUE TITLE
Bug: Border hangs out at the bottom of the screen if you go to fullscreen after tutorial

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/Industry-Game#24]
![Screenshot 2022-02-09 9 40 16 AM](https://user-images.githubusercontent.com/77758464/153224360-4a61df8d-05fb-48c8-a6b7-04bc47cf4a4e.png)

**Comment by robtech21** [comment]
(this is present on both the repl development and GitHub stable version)

**Comment by Jackal-42** [comment]
Fixed I think
