### ISSUE TITLE
??? - Having a decimal value in funds

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/Industry-Game#27]
![Screenshot 2022-03-04 10 22 36 AM](https://user-images.githubusercontent.com/77758464/156790792-352b3e51-0b1a-44d9-9b73-ef84f892cdeb.png)

I don't think this is a feature, right?

A suggestion to fix this would be to check for a float and change it back to an integer or round it up.

**Comment by Jackal-42** [comment]
oh I think I know what this may be, it probably has to do with the valves splitting items. Yes rounding is a good plan
