### ISSUE TITLE
Fix Airbrake

### ISSUE THREAD

**Issue by Jackal-42** [Jackal-42/Industry-Game#30]
I can't seem to figure it out at the moment so I will put it here. Airbrake does not get initialized from the core.js file, but it does from the command line. I am focusing on more important stuff at the moment but it would be very helpful to have.

**Comment by robtech21** [comment]
Does this still need to be fixed? I might have some time later...

**Comment by Jackal-42** [comment]
Yeah, I was hoping you could look at it later so I could focus in the game features. The initialization code should still be in the core.js file but commented out. For testing purposes, I can text you the credentials to the Airbrake account so you know if it works

**Comment by robtech21** [comment]
Implemented kind of, see #33 for further instruction.
