### ISSUE TITLE
Console Log Error

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/Industry-Game#31]
`Uncaught SyntaxError: Cannot use import statement outside a module core.js:3`

Line three of `core.js` is the import statement for airbrake

**Comment by Jackal-42** [comment]
You need to add `type="module"` to the <script> tag containing `core.js` in the `index.html` file.

**Comment by robtech21** [comment]
Okay, update.

* Changed the script type to `"module"` in `index.html`
* Changed the path of the import to `/node_modules/airbrake/lib/airbrake.js`

New error:

```
airbrake.js:1 Uncaught ReferenceError: require is not defined
    at airbrake.js:1:11
```


Current theory is that this is legacy code for NodeJS and it now uses `import` instead of `require` but I'll do some digging
