### ISSUE TITLE
[Airbrake] [Production] assignment to undeclared variable airbrake

### ISSUE THREAD

**Issue by Jackal-42** [Jackal-42/Industry-Game#32]
**Airbrake error:** [#2938](https://officialjacklarson-gmail-com.airbrake.io/projects/402502/groups/3245306784457712938)
**Airbrake project:** Industry-Game

**Error type:** `ReferenceError`
**Error message:** `` assignment to undeclared variable airbrake ``
**Where:** `<no information>`
**Occurred at:** Apr 05, 2022 16:13:15 UTC
**First seen at:** Apr 05, 2022 16:05:14 UTC
**Occurrences:** 10 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [http://127.0.0.1:5500/index.html](http://127.0.0.1:5500/index.html)
**File:** `/PROJECT_ROOT/index.html`

**Backtrace:**
```
/PROJECT_ROOT/index.html:84:in 
```
Visit [Airbrake error](https://officialjacklarson-gmail-com.airbrake.io/projects/402502/groups/3245306784457712938?tab=notice-detail) to view the full backtrace.

**Comment by robtech21** [comment]
It occurs where you put in the stuff like the ID and key for `Notifier` to define `airbrake`
