### ISSUE TITLE
Improve Docs (revised with detail)

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/Industry-Game#4]
* Remove comment about me not learning JavaScript
* Make framework steps less boring
* More comprehensive detail of function and class documentation
* (Optional) put documentation on the GitHub pages

**Comment by Jackal-42** [comment]
Alright, I can work on that after I do a bit of a code cleanup over thanksgiving break. I realized that I used arrays in some places I should have used Objects and I think I can fix that and make the code more readable.

**Comment by robtech21** [comment]
Okay, thanks. I'll also put one or two of the points from the email into a separate issue.

**Comment by Jackal-42** [comment]
I added the Area and CodeBlock classes, and maybe functions will come later but I wanted to focus on more important things and they didn't seem needed.
