### ISSUE TITLE
Issues for Most Recent Commit

### ISSUE THREAD

**Issue by robtech21** [Jackal-42/Industry-Game#6]
This is a first glance list of issues from the latest commit:

* Custom cursor isn't in the right place
* Clicking next to the refinery opens up the UI for it instead of placing a pipe (bug or missing texture?)

**Comment by Jackal-42** [comment]
It isn't supposed to be a custom cursor (That's a bit ugly) it is supposed to show to the bottom right of the actual cursor. If there is a better way to display which one is selected, I can do that.

The refinery textures are messed up until I get the new ones from our graphics designer. The new engine requires them to be rendered in their native resolution. The facilities should be 2x2, not 1x1.
